set(JPEG_ROOT_DIR "${CMAKE_CURRENT_LIST_DIR}/../../deps/kindlepw2/libjpeg")

set(_OLD_CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ${CMAKE_FIND_ROOT_PATH_MODE_INCLUDE})
set(_OLD_CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ${CMAKE_FIND_ROOT_PATH_MODE_LIBRARY})

set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)

find_path(JPEG_INCLUDE_DIR
    NAMES jpeglib.h
    PATHS ${JPEG_ROOT_DIR}/include
	NO_DEFAULT_PATH
)

find_library(JPEG_LIBRARIES
    NAMES jpeg
    PATHS ${JPEG_ROOT_DIR}/lib
	NO_DEFAULT_PATH
)

if(JPEG_INCLUDE_DIR AND JPEG_LIBRARIES)
    set(JPEG_FOUND TRUE)
else()
    set(JPEG_FOUND FALSE)
endif()

mark_as_advanced(JPEG_INCLUDE_DIR JPEG_LIBRARIES)

set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ${_OLD_CMAKE_FIND_ROOT_PATH_MODE_INCLUDE})
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ${_OLD_CMAKE_FIND_ROOT_PATH_MODE_LIBRARY})
