set(PNG_ROOT_DIR "${CMAKE_CURRENT_LIST_DIR}/../../deps/kindlepw2/libpng")

set(_OLD_CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ${CMAKE_FIND_ROOT_PATH_MODE_INCLUDE})
set(_OLD_CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ${CMAKE_FIND_ROOT_PATH_MODE_LIBRARY})

set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)

find_path(PNG_INCLUDE_DIR
    NAMES png.h
    PATHS ${PNG_ROOT_DIR}/include
	NO_DEFAULT_PATH
)

find_library(PNG_LIBRARIES
    NAMES png16
    PATHS ${PNG_ROOT_DIR}/lib
	NO_DEFAULT_PATH
)

if(PNG_INCLUDE_DIR AND PNG_LIBRARIES)
    set(PNG_FOUND TRUE)
else()
    set(PNG_FOUND FALSE)
endif()

mark_as_advanced(PNG_INCLUDE_DIR PNG_LIBRARIES)

set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ${_OLD_CMAKE_FIND_ROOT_PATH_MODE_INCLUDE})
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ${_OLD_CMAKE_FIND_ROOT_PATH_MODE_LIBRARY})
