set(ZLIB_ROOT_DIR "${CMAKE_CURRENT_LIST_DIR}/../../deps/kindlepw2/zlib")

set(_OLD_CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ${CMAKE_FIND_ROOT_PATH_MODE_INCLUDE})
set(_OLD_CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ${CMAKE_FIND_ROOT_PATH_MODE_LIBRARY})

set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)

find_path(ZLIB_INCLUDE_DIR
    NAMES zlib.h
    PATHS ${ZLIB_ROOT_DIR}/include
	NO_DEFAULT_PATH
)

find_library(ZLIB_LIBRARIES
    NAMES z
    PATHS ${ZLIB_ROOT_DIR}/lib
	NO_DEFAULT_PATH
)

if(ZLIB_INCLUDE_DIR AND ZLIB_LIBRARIES)
    set(ZLIB_FOUND TRUE)
else()
    set(ZLIB_FOUND FALSE)
endif()

mark_as_advanced(ZLIB_INCLUDE_DIR ZLIB_LIBRARIES)

set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ${_OLD_CMAKE_FIND_ROOT_PATH_MODE_INCLUDE})
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ${_OLD_CMAKE_FIND_ROOT_PATH_MODE_LIBRARY})
